// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {storage} from '../models';

export function CopyItem(arg1:number):Promise<void>;

export function DeleteItem(arg1:number):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetHistory(arg1:number,arg2:number):Promise<Array<storage.ClipboardItem>>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function Search(arg1:string):Promise<Array<storage.ClipboardItem>>;

export function TogglePin(arg1:number):Promise<void>;
